### ISSUE TITLE
Add documentation to readme.md

### ISSUE THREAD

**Issue by chrisevans9629** [EaseLibrary/Ease#1]
## Addition to Installation
Installation could show how you use them in your unit tests.
Ex. use UnityContainerTestBase as the base of your test class
## Examples

Examples could be added to the readme so that it's easier to get started.
I created a sample that shows how to use Ease that might be useful to add to the readme
[sample here](https://github.com/chrisevans9629/EaseSamples/blob/master/EaseSamples/MathExamples.cs)

**Comment by chowarth** [comment]
I agree that it's a shame that there isn't a sample project included within the library solution itself, however, there is a separate repo at found [here](https://github.com/EaseLibrary/XamarinFormsDemos) that covers example usage 😃

**Comment by duanenewman** [comment]
As @chowarth pointed out, I do have a sample, but failed to link. I'll look at updating the readme with references to the samples as well as adding sample code here.
