### ISSUE TITLE
xUnit Support

### ISSUE THREAD

**Issue by chowarth** [EaseLibrary/Ease#3]
Really like the approach that you've taken with this and wondering if you had had any thoughts about expanding the library to support xUnit?

I know this would require a massive refactor of the current implementation and I wouldn't mind giving it a go if you have any ideas on the approach.

**Comment by duanenewman** [comment]
I've been thinking about this as I'm using xUnit with a client now. I see your PR and will review.

**Comment by duanenewman** [comment]
Thanks for working on this Chris! @chowarth
