### ISSUE TITLE
Rename VerifyNavigation to VerifyNavigationNavigateAsync

### ISSUE THREAD

**Issue by duanenewman** [EaseLibrary/Ease#5]
With some of the incoming change we should refactor the `VerifyNavigation` method to `VerifyNavigationNavigateAsync` to lower confusion with multiple methods on INavigationService (i.e. GoBackAsync)

**Comment by chowarth** [comment]
@duanenewman  got a couple of things that, after using the most recent release, I'd like to add, I can do this as a part of that:
- Would `VerifyNavigationNavigateAsync` or `VerifyNavigateAsync` be more preferred?
  - I feel the latter would be easier to read and maybe less confusing than `*NavigationNavigate*`

**Comment by duanenewman** [comment]
Thinking about this. I want to try to avoid something that might collide with what a user would want to do and make it clear we are validating the Prism INavigationService.. Maybe VerifyPrismNavigationAsync?

**Comment by chowarth** [comment]
That sounds like a good idea, will get them updated 😃

**Comment by duanenewman** [comment]
@chowarth I think I'd prefer a parameterless overload vs optional parameter, but otherwise that would be helpful. I think also that instead of a dummy lambda `() => {}` you could just do `null`. I'd rather this get tracked separately so I'm going create a new issue for that.
